/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellPipelinesRouteImport } from './routes/_shell.pipelines'
import { Route as ShellPipelinesIndexRouteImport } from './routes/_shell.pipelines.index'
import { Route as ShellSessionsSessionIdRouteImport } from './routes/_shell.sessions.$sessionId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellPipelinesRunsRouteImport } from './routes/_shell.pipelines.runs'
import { Route as ShellProjectsProjectIdSettingsRouteImport } from './routes/_shell.projects.$projectId_.settings'
import { Route as ShellPipelinesRunsRunIdRouteImport } from './routes/_shell.pipelines.runs_.$runId'
import { Route as ShellProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_shell.projects.$projectId_.sessions.$sessionId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelinesRoute = ShellPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelinesIndexRoute = ShellPipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellPipelinesRoute,
} as any)
const ShellSessionsSessionIdRoute = ShellSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelinesRunsRoute = ShellPipelinesRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ShellPipelinesRoute,
} as any)
const ShellProjectsProjectIdSettingsRoute =
  ShellProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellPipelinesRunsRunIdRoute = ShellPipelinesRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => ShellPipelinesRoute,
} as any)
const ShellProjectsProjectIdSessionsSessionIdRoute =
  ShellProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId_/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/pipelines': typeof ShellPipelinesRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/pipelines/runs': typeof ShellPipelinesRunsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/pipelines/': typeof ShellPipelinesIndexRoute
  '/pipelines/runs/$runId': typeof ShellPipelinesRunsRunIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/': typeof ShellIndexRoute
  '/pipelines/runs': typeof ShellPipelinesRunsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/pipelines': typeof ShellPipelinesIndexRoute
  '/pipelines/runs/$runId': typeof ShellPipelinesRunsRunIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/pipelines': typeof ShellPipelinesRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/pipelines/runs': typeof ShellPipelinesRunsRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/_shell/pipelines/': typeof ShellPipelinesIndexRoute
  '/_shell/pipelines/runs_/$runId': typeof ShellPipelinesRunsRunIdRoute
  '/_shell/projects/$projectId_/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/_shell/projects/$projectId_/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipelines'
    | '/settings'
    | '/terminals'
    | '/pipelines/runs'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/pipelines/'
    | '/pipelines/runs/$runId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/terminals'
    | '/'
    | '/pipelines/runs'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/pipelines'
    | '/pipelines/runs/$runId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/pipelines'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/'
    | '/_shell/pipelines/runs'
    | '/_shell/projects/$projectId'
    | '/_shell/sessions/$sessionId'
    | '/_shell/pipelines/'
    | '/_shell/pipelines/runs_/$runId'
    | '/_shell/projects/$projectId_/settings'
    | '/_shell/projects/$projectId_/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines': {
      id: '/_shell/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof ShellPipelinesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines/': {
      id: '/_shell/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof ShellPipelinesIndexRouteImport
      parentRoute: typeof ShellPipelinesRoute
    }
    '/_shell/sessions/$sessionId': {
      id: '/_shell/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ShellSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines/runs': {
      id: '/_shell/pipelines/runs'
      path: '/runs'
      fullPath: '/pipelines/runs'
      preLoaderRoute: typeof ShellPipelinesRunsRouteImport
      parentRoute: typeof ShellPipelinesRoute
    }
    '/_shell/projects/$projectId_/settings': {
      id: '/_shell/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ShellProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines/runs_/$runId': {
      id: '/_shell/pipelines/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/pipelines/runs/$runId'
      preLoaderRoute: typeof ShellPipelinesRunsRunIdRouteImport
      parentRoute: typeof ShellPipelinesRoute
    }
    '/_shell/projects/$projectId_/sessions/$sessionId': {
      id: '/_shell/projects/$projectId_/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ShellProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellPipelinesRouteChildren {
  ShellPipelinesRunsRoute: typeof ShellPipelinesRunsRoute
  ShellPipelinesIndexRoute: typeof ShellPipelinesIndexRoute
  ShellPipelinesRunsRunIdRoute: typeof ShellPipelinesRunsRunIdRoute
}

const ShellPipelinesRouteChildren: ShellPipelinesRouteChildren = {
  ShellPipelinesRunsRoute: ShellPipelinesRunsRoute,
  ShellPipelinesIndexRoute: ShellPipelinesIndexRoute,
  ShellPipelinesRunsRunIdRoute: ShellPipelinesRunsRunIdRoute,
}

const ShellPipelinesRouteWithChildren = ShellPipelinesRoute._addFileChildren(
  ShellPipelinesRouteChildren,
)

interface ShellRouteChildren {
  ShellPipelinesRoute: typeof ShellPipelinesRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellSessionsSessionIdRoute: typeof ShellSessionsSessionIdRoute
  ShellProjectsProjectIdSettingsRoute: typeof ShellProjectsProjectIdSettingsRoute
  ShellProjectsProjectIdSessionsSessionIdRoute: typeof ShellProjectsProjectIdSessionsSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellPipelinesRoute: ShellPipelinesRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellSessionsSessionIdRoute: ShellSessionsSessionIdRoute,
  ShellProjectsProjectIdSettingsRoute: ShellProjectsProjectIdSettingsRoute,
  ShellProjectsProjectIdSessionsSessionIdRoute:
    ShellProjectsProjectIdSessionsSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
